# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lilo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lilo
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON'

  target 'LiloTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiloUITests' do
    # Pods for testing
  end

end
